### PR TITLE
5 endpoint

### LINKED ISSUE #5: 5 Endpoint
Details

1. This endpoint should follow the pattern of POST /api/v0/vendors, and should pass ALL attributes required to create a vendor (name, description, contact_name, contact_phone, and credit_accepted) as JSON in the body of the request. (In postman, navigate to Body tab, select raw and change the format to JSON instead of Text)
2. This endpoint should create a new vendor resource.
3. A successful response will return a response with a 201 status code, and return the newly created vendor resource.
4. If any number of attributes are left out in the body of the request, a status code of 400, as well as a descriptive error message should be sent back in the response.
5. Validating the presence of a boolean value can be tricky since false is evaluated as nil. Validating the presence of a field that could be false will generate some a validation error when we don’t mean it to. We’d suggest creating your own [custom validation](https://guides.rubyonrails.org/active_record_validations.html#custom-methods) for validating the presence of a boolean field.

`Example #1 😁
Request:

   POST /api/v0/vendors
   Content-Type: application/json
   Accept: application/json
Body:

 {
     "name": "Buzzy Bees",
     "description": "local honey and wax products",
     "contact_name": "Berly Couwer",
     "contact_phone": "8389928383",
     "credit_accepted": false
 }`

`Response: status: 201

 {
     "data": {
         "id": "56542",
         "type": "vendor",
         "attributes": {
             "name": "Buzzy Bees",
             "description": "local honey and wax products",
             "contact_name": "Berly Couwer",
             "contact_phone": "8389928383",
             "credit_accepted": false
         }
     }
 }`

`Example #2 😭
Request:

     POST /api/v0/vendors
     Content-Type: application/json
     Accept: application/json
Body:

   {
       "name": "Buzzy Bees",
       "description": "local honey and wax products",
       "credit_accepted": false
   }
Response: status: 400

 {
     "errors": [
         {
             "detail": "Validation failed: Contact name can't be blank, Contact phone can't be blank"
         }
     ]
 }`

### PR DESCRIPTION
**Pull request by odellmac4**
## Type of change
- [x] New feature
- [ ] Bug Fix
- [x] Test
- [ ] Refactor/Style

## Description
Relevant User Story(s): 

-**Happy Path: endpoint 5**

*Brief summary of the change(s) included in this pull request*
-**Created a test to create a vendor by passing params in the body of the request**
-**Ceated `create` action in vendors controller **
-**Explicity returned statuses if a vendor was/was not created**

## Implements/Fixes:

-**Still need to complete sad path**

description closes #

## Check the correct boxes
- [ ] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

## Testing Changes
- [x] No Tests have been changed
- [ ] Some Tests have been changed
- [ ] All of the Tests have been changed

*Please describe what in the world happened if tests are broken*

## Checklist:
- [x] My code has no unused/commented out code
- [x] I have reviewed my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have fully tested my code

### CODE REVIEW

File: app/controllers/api/v0/vendors_controller.rb [hunk 1]
```diff
@@ -4,8 +4,31 @@ def show
...
   end
 
+  def create
+    vendor = Vendor.new(vendor_params)
+    if vendor.save
+      # These statuses are explicitly returning the status responses we want based on requirements
+      render json: VendorSerializer.new(vendor), status: :created
+    else
+      render json: { errors: vendor.errors.full_messages }, status: :bad_request
+    end
```
Comment (yainporter) [inline app/controllers/api/v0/vendors_controller.rb:14]: Nice error handling here! I didn't think to add that in the first go-round I was trying to handle the bad request

**Review by yainporter — APPROVED** [review]
Looks good, there will be some refactoring once we get started on using a Serializer
